version: '3.9'

services:
  py-api-ms-db:
    image: postgres:14.7
    container_name: py-api-ms-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:     
      - py_api_ms_dbdata:/var/lib/postgresql/data
    networks:
      - py-api-ms-network
  py-api-ms:
    depends_on:
      - py-api-ms-db
    build:
      context: .
      dockerfile: Dockerfile
    image: py-api-ms
    container_name: py-api-ms
    restart: always
    env_file: 
      - .env
    environment:
      FLASK_ENV: $FLASK_ENV
      FLASK_DEBUG: $FLASK_DEBUG
      APP_SETTINGS: $APP_SETTINGS
      SECRET_KEY: $SECRET_KEY
      APP_PORT: $APP_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOSTNAME: $POSTGRES_HOSTNAME
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5000:5000"
    volumes:     
      - .:/usr/src/app
    networks:
      - py-api-ms-network

networks:
  py-api-ms-network:
    driver: bridge

volumes:
  py_api_ms_dbdata:
